#!/bin/sh 
#SBATCH --job-name="blastN_pla2"
#SBATCH --mem=40G
#for i in `seq 1 1 10`; do
cp /home/ibv/jdurban/Dany/Cc/CAP3/pla2.fasta $SLURMTMP;
#done
cd $SLURMTMP
### Script per llançar blastx usant SLURM_ARRAY ###
#blastn -task blastn -db /home/ibv/jdurban/db/nt/nt -evalue 0.001 -outfmt 5 -query resultado${SLURM_ARRAY_TASK_ID} -show_gis -max_target_seqs 1 -max_hsps 1 -num_threads 2 -out /home/ibv/jdurban/Dany/Ca/CAP3/blastresults/Repeat/blastN_toxins_$SLURM_ARRAY_TASK_ID
blastn -task blastn -db /home/ibv/jdurban/db/nt/nt -evalue 0.001 -outfmt 5 -query pla2.fasta -show_gis -max_target_seqs 1 -max_hsps 1 -num_threads 2 -out /home/ibv/jdurban/Dany/Cc/CAP3/pla2_blast_prova 

mv * $SLURM_SUBMIT_DIR
exit
#sbatch -p Q-low -n 6 --mem=15G --array=0-24 --job-name=blastX17 ~/scripts/blastX17
#qsub -N blastX18 -q Q-med -t 0-24 -l nodes=5 ~/scripts/blastx
