#!/bin/bash
##SBATCH --job-name="tran_Oas_Tv"
##SBATCH --mem=300G
cp /home/ibv/jdurban/Dany/Tv_1/Tv_1_1-paired_prinseq_good_Rr78.fastq_pairs_R1.fastq /home/ibv/jdurban/Dany/Tv_1/Tv_1_2-paired_prinseq_good__vWo.fastq_pairs_R2.fastq $SLURMTMP
cd $SLURMTMP
for i in 53; do
transrate --assembly /home/ibv/jdurban/Dany/Tv_1/Oases/Tv_1_${i}/transcripts.fa --left Tv_1_1-paired_prinseq_good_Rr78.fastq_pairs_R1.fastq --right Tv_1_2-paired_prinseq_good__vWo.fastq_pairs_R2.fastq --output /home/ibv/jdurban/Dany/Tv_1/Oases/Tv_1_${i} --threads 4 --loglevel error; done
mv * $SLURM_SUBMIT_DIR
exit

#run_high.sh transrate_prova transrate_prova nodes=6
