#!/bin/bash
#SBATCH --job-name="trin_Tv_1"
#SBATCH --mem=100G

cp /home/ibv/jdurban/Dany/Tv_1/Tv_1_1-paired_prinseq_good_Rr78.fastq_pairs_R1.fastq /home/ibv/jdurban/Dany/Tv_1/Tv_1_2-paired_prinseq_good__vWo.fastq_pairs_R2.fastq $SLURMTMP
cd $SLURMTMP

Trinity --seqType fq --max_memory 100G --left Tv_1_1-paired_prinseq_good_Rr78.fastq_pairs_R1.fastq --right Tv_1_2-paired_prinseq_good__vWo.fastq_pairs_R2.fastq --SS_lib_type RF --output /home/ibv/jdurban/Dany/Tv_1/Trinity/ --CPU 6 --min_contig_length 100 --full_cleanup > /home/ibv/jdurban/Dany/Tv_1/Trinity/Trinityrun.log 2>/home/ibv/jdurban/Dany/Tv_1/Trinity/Trinity_error.txt --verbose
mv * $SLURM_SUBMIT_DIR
exit
