#!/bin/sh 
### Script per llançar blastx usant SLURM_ARRAY ###
#SBATCH --job-name="Blast_Bjar"
#SBATCH --mem=15G
cp -r /home/ibv/jdurban/MinION/Bjararaca/Bjararaca.fasta $SLURMTMP
cd $SLURMTMP
blastn -task blastn -db /home/ibv/jdurban/db/nt/nt -evalue 0.001 -outfmt 5 -query Bjararaca.fasta -show_gis -max_target_seqs 1 -max_hsps 1 -num_threads 4 -out blastN_Bjararaca

mv * /home/ibv/jdurban/MinION/Bjararaca/blast
exit
#sbatch -p Q-low -n 6 --mem=15G --array=0-24 --job-name=blastX17 ~/scripts/blastX17
#qsub -N blastX18 -q Q-med -t 0-24 -l nodes=5 ~/scripts/blastx
